### ISSUE TITLE
DbSet property of the MyContext can be not-nullable

### ISSUE THREAD

**Issue by christiannagel** [csharpfritz/InstantAPIs#10]
by invoking the `Set` method of the base class.

I'm creating a pull request for the readme and MyContext.cs

Great ideas with this library! Thanks!

**Comment by csharpfritz** [comment]
Thanks @christiannagel !  

@jamesmontemagno sent an update to the README to show that multiple `DbSet<T>` objects are consumed in generating APIs.  I'll apply a similar fix to the Addresses sample he added
