### ISSUE TITLE
Need to have ability to exclude specific entities or properties

### ISSUE THREAD

**Issue by kraghavk** [csharpfritz/InstantAPIs#2]
I love the idea behind this project. This is great and I am looking forward to this becoming more mature, stable and famous!

The following configuration options might be required in a lot of cases:

1. Exclude specific entities: I might be fine with exposing a 100 other entities within my DbContext in this way. But I need the ability to exclude some (for example User entity), so that I can create my own endpoints with my own business logic for it.
2. Exclude specific properties of an entity: In some cases, there may be properties that are not meant to be modified directly by a PUT or a POST request. For example, columns that are updated behind the scenes via some business logic.

Thanks,
Raghu

**Comment by verbedr** [comment]
Suggestion for the properties.  In true DDD fashion, they need to be read-only (private setter). Could this work? It would drop the need for complex configuration of includes/excludes.

**Comment by kraghavk** [comment]
That would absolutely work and eliminate messy configuration.
