### ISSUE TITLE
NuGet version for prerelease

### ISSUE THREAD

**Issue by christiannagel** [csharpfritz/InstantAPIs#29]
It's great to have it already available on NuGet :-)

I think the version number should have a text included, such as *preview*, *beta*, *alpha*, such as *0.1.0-preview.1.4242.
With a text in the version number, the package is only shown when selecting **include prerelease**, and not leads to *production quality*.

**Comment by csharpfritz** [comment]
I can appreciate this perspective... but that first NuGet package provided the minimum feature set that met my original definition.

I agree with you on someone picking it up and considering it "production quality" and it could certainly be used at that level, but you're right in that it's not at 'enterprise quality' with logging, error handling, and more

**Comment by christiannagel** [comment]
I was thinking about the first major version 1.0 - with logging, error handling, but this is probably just me.

**Comment by csharpfritz** [comment]
@christiannagel - totally agree, first major version that should be considered "production ready" would be a 1.0 release

I'm pushing a 0.2.0-preview today with the configuration updates for including and excluding tables.

**Comment by christiannagel** [comment]
Closing this, I already can see multiple preview versions available on NuGet, thanks 👍
