### ISSUE TITLE
Enhance ConfigBuilder

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/InstantAPIs#3]
- [x] Strongly-typed references to the tables to Include / Exclude ( see #2 )
- [ ] Inject validation or other logic OnBegin and OnAfter
- [ ] Map to a ViewModel?
- [x] Allow definition of alternate URLs

**Comment by verbedr** [comment]
Fritz,
A suggestion ... don't call them tables. Especially when it is to be mapped on Entity Framework Core.  Call them "entities".

**Comment by csharpfritz** [comment]
> Fritz, A suggestion ... don't call them tables. Especially when it is to be mapped on Entity Framework Core. Call them "entities".

Yep... For the JSON API feature, we called them Entities.  For EF, I think we can revisit that naming

**Comment by csharpfritz** [comment]
Moved last items on this checklist to their own issues:

#52 and #53

**Comment by jlopez788** [comment]
The config should allow for soft-delete entities.
