### ISSUE TITLE
Docs site

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/InstantAPIs#32]
Let's put together a docs folder along with a GitHub action to generate a docs site to live on the ghpages branch and GitHub static site that goes with this repository.

We should also add a link/shield to the README that points to the docs site

**Comment by QuinntyneBrown** [comment]
I can grab this one.

**Comment by QuinntyneBrown** [comment]
Is there an existing repo that basically implementing the same behaviour you are looking for? We are going to need a branch named gh-pages and a bit of configuration in this repository for starters.

**Comment by csharpfritz** [comment]
> Is there an existing repo that basically implementing the same behaviour you are looking for? We are going to need a branch named gh-pages and a bit of configuration in this repository for starters.

Check out the configuration for the BlazorWebFormsComponents at:  https://github.com/fritzandfriends/blazorwebformscomponents
