### ISSUE TITLE
Export the endpoint to a file/class for verification

### ISSUE THREAD

**Issue by fasteddys** [csharpfritz/InstantAPIs#33]
Hello, is there an option to export the endpoints generated to a log or a `class` file for us to view or `generate a menu` context, or generic Ajax caller

**Comment by csharpfritz** [comment]
Good point...  when your app is running and if you added OpenAPI to your application, you _COULD_ grab the `swagger.json` file to inspect.

I like your suggestion of adding something more native to the tool.

**Comment by csharpfritz** [comment]
I do still like the logging option of this...  creating a separate issue
