### ISSUE TITLE
Spaces vs. Tabs

### ISSUE THREAD

**Issue by Stelzi79** [csharpfritz/InstantAPIs#42]
I have looked at several .csproj files and they all use Spaces for indentation.

It might be a good idea to put an .editorconfig file in that ensures that only Tabs instead of Spaces are used for indentations.

**Comment by csharpfritz** [comment]
Yea..  Let's add an editorConfig that dictates tabs and start building it out

**Comment by JasonBock** [comment]
I'd go one step further and say that this project needs an `.editorconfig` to enforce more than just tabs vs. spaces. Do I use `var`, or the type name? Do I use expression-bodied members when possible, or not? There are a lot of styling aspects to code that an `.editorconfig` can enforce.
