### ISSUE TITLE
编译缺少文件

### ISSUE THREAD

**Issue by zhangning123798** [csharpfritz/InstantAPIs#54]
![image](https://user-images.githubusercontent.com/6867784/155918954-844afc4f-df66-43b6-afd3-67be709e4154.png)

**Comment by gldraphael** [comment]
Can you reproduce this on the command line? (google translate: 你能在命令行上重现这个吗？)

```
git clone https://github.com/csharpfritz/InstantAPIs.git
cd InstantAPIs
dotnet build 
```

**Comment by zhangning123798** [comment]
![image](https://user-images.githubusercontent.com/6867784/155932042-1d2283df-5c8e-43a0-be08-d134e8c06f78.png)

**Comment by Stelzi79** [comment]
The error is in English `CS0016: Could not write to output file` (or what I could find about it).

**Comment by zhangning123798** [comment]
这个文件不在解决方案中，是如何生成得，为什么不能写入输出文件，找不到这个文件

**Comment by gldraphael** [comment]
The `*.sourcelink.json` file is autogenerated. More about source-linking [here](https://github.com/dotnet/sourcelink/blob/main/docs/README.md).

![image](https://user-images.githubusercontent.com/10794213/156109843-594bdd82-bd06-461b-8100-bd77672aa694.png)


A temporary workaround would be to disable source-linking by removing the following lines from `Fritz.InstantAPIs.csproj`:

```xml
<EmbedUntrackedSources>true</EmbedUntrackedSources>

<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
```

**Comment by zhangning123798** [comment]
多谢，解决了

**Comment by csharpfritz** [comment]
Closing with a work-around
