### ISSUE TITLE
Custom API Endpoints

### ISSUE THREAD

**Issue by ChessGeekBoy** [csharpfritz/InstantAPIs#64]
As of now, (correct me if I'm wrong) InstantAPIs supports creating all API endpoints (HTTP GET, GET by ID, POST, PATCH, PUT, and DELETE) or just one. It might be nice if it allowed the user to customize which ones they create. For example, a user might only want HTTP GET and DELETE endpoints.

**Comment by csharpfritz** [comment]
This is already possible with the IncludeTable configuration instruction.  The configuration suggested is possible with the following:

```
app.MapInstantAPIs<MyContext>(config =>
{
	config.IncludeTable(db => db.Contacts, ApiMethodsToGenerate.Get | ApiMethodsToGenerate.Delete, "addressBook");
});
```
