### ISSUE TITLE
GitHub action to publish to NuGet

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/InstantAPIs#8]
- [x] Generate NuGet package
- [x] Publish new commits to **main** branch to NuGet

**Comment by timheuer** [comment]
For the second task of push of course you'll need your API key but simple: https://github.com/timheuer/alexa-skills-dotnet/blob/master/.github/workflows/build.yml#L108-L109 (assume no signing)

**Comment by csharpfritz** [comment]
I'm also going to make the main branch protected and establish a dev branch for collaboration

**Comment by timheuer** [comment]
Smart.  FWIW, I usually have two workflows: "ci" and "build/publish" -- it may be duplicative (you can now use composites) but it also avoids a lot of `if:` stuff...I'm happy to contribute the separation with composite actions for the common.

**Comment by csharpfritz** [comment]
Now I'm thinking...  keep main as the default branch, and add a `release` branch and when a PR is merged there the release and publish to NuGet is done.  Then the action only happens on that branch, and both main and release are protected

**Comment by csharpfritz** [comment]
Done.. PRs to `release` are built and tested.  When merged, the content of the `release` branch is sent to NuGet
